### ISSUE TITLE
Provide instructions for using Subspace in a CMake-based project

### ISSUE THREAD

**Issue by danakj** [chromium/subspace#226]
We have some instructions for checking out and building Subspace, but no integration instructions.

Presumably this is easy for CMake pros, but some steps would be good, that include disabling CIR/Subdoc. And that include enabling the [clang-tidy](https://github.com/chromium/subspace/pull/219)! Once it's merged.

Possibly we should consider vcpkg or something?

@dj2 From your past submissions it seems like you were optimizing this path, do you have any opinions or help you could lend?

**Comment by dj2** [comment]
I'll try to write down some steps for the case where you `submodule` in `subspace`. For the world of using `FindPackage` or `vcpkg` that's outside the realm of what I usually do.

**Comment by danakj** [comment]
Cool :) Very appreciated!

**Comment by dj2** [comment]
This might take a bit longer then expected. Github wouldn't let me update my fork, so I deleted it, and now it won't let me fork the subspace repo. I just get an `oops` message. Will try again in a few days to see if they've fixed whatever is going on ....

**Comment by danakj** [comment]
Weird 😕

**Comment by danakj** [comment]
Is Github still giving problems?
